version: '3.9'

services:
  djangoapp:
    container_name: djangoapp
    # command: tail -f /dev/null
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./djangoapp:/djangoapp
      # - ./data/web/static:/data/web/static/
      # - ./data/web/media:/data/web/media/
      - ./scripts/:/scripts/
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - psql
     #psql: 
      #condition: service_healthy
  psql:
    container_name: psql
    image: postgres:13-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./dotenv_files/.env    
     #healthcheck:
      #test: ["CMD-SHELL", "while ! pg_isready -U $POSTGRES_USER; do sleep 1; done && python manage.py migrate"]
      
